/** @type {import('tailwindcss').Config} */
module.exports = {

  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
  
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
        "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      
      colors: {
        "dark" : "#00CDB8",
        "light" : "#00CDB8",
        "cupcake" : "#EEAF3A",
        "bumblebee" : "#FFA551",
        "emerald" : "#F68067",
        "corporate" : "#67CBA0",
        "synthwave" : "#FFD200",
        "retro" : "#DC8850",
        "cyberpunk ": "#CE74FF",
        "valentine" : "#66B1B3",
        "halloween" : "#42AA00",
        "garden" : "#5C7F67",
        "forest" : "#1DB8AB",
        "aqua" : "#FFE999",
        "lofi" : "#262626",
        "pastel" : "#B4E9D6",
        "fantasy" : "#FF8600",
        "wireframe" : "#B8B8B8",
        "black" : "#373737",
        "luxury" : "#513448",
        "dracula" : "#FFB86C",
        "cmyk" : "#FFF232",
        "autumn" : "#D59B6A",
        "business" : "#EA6947",
        "acid" : "#C8FF00",
        "lemonade" : "#EDD000",
        "night" : "#F471B5",
        "coffee" : "#10576D",
        "winter" : "#C148AC",
        "dim" : "#C792E9",
        "nord" : "#88C0D0",
        "sunset" : "#B387FA",
      }
    },
  },
  // plugins: [],
  plugins: [require("daisyui")],
};
